// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86O34pIA5mjp1_qPR7PTQVWpCRRpxffQ',
    appId: '1:276976121047:web:0407eed33ae718e2152c92',
    messagingSenderId: '276976121047',
    projectId: 'rentitease-65e49',
    authDomain: 'rentitease-65e49.firebaseapp.com',
    storageBucket: 'rentitease-65e49.firebasestorage.app',
    measurementId: 'G-QSDWLB9JX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GI1ew-EyBzea-wLwvQUiCPsJXW6Ls8k',
    appId: '1:276976121047:android:72bf8e94f2676aea152c92',
    messagingSenderId: '276976121047',
    projectId: 'rentitease-65e49',
    storageBucket: 'rentitease-65e49.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_CspcD-yGp_auavvMaq9GtrZSBg1EKsE',
    appId: '1:276976121047:ios:9fd3a5bc0af061f6152c92',
    messagingSenderId: '276976121047',
    projectId: 'rentitease-65e49',
    storageBucket: 'rentitease-65e49.firebasestorage.app',
    iosBundleId: 'com.RentItEase.app.mobileApp',
  );
}
