// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions
{
static FirebaseOptions get currentPlatform 
{
if (kIsWeb) 
{
      return web;
    }
    switch (defaultTargetPlatform)
{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaz2OcIFE9Yp1ktdkuAdjxoyeKEzGj5o0',
appId: '1:388317975025:web:ce58332801bad5726f7450',
messagingSenderId: '388317975025',
projectId: 'RentItEase-c762e',
authDomain: 'RentItEase-c762e.firebaseapp.com',
storageBucket: 'RentItEase-c762e.firebasestorage.app',
measurementId: 'G-7CDK25JWER',
  );

static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRSTrO0DQ0AdkPV0u83wK1kRrQqNkgco',
appId: '1:388317975025:android:cf64d9a322e699c56f7450',
messagingSenderId: '388317975025',
projectId: 'RentItEase-c762e',
storageBucket: 'RentItEase-c762e.firebasestorage.app',
  );
static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXEhBvJHbiYmsC36dUDHW94hM4FYFsx4',
appId: '1:388317975025:ios:b3bf006fa7f0b59f6f7450',
messagingSenderId: '388317975025',
projectId: 'RentItEase-c762e',
storageBucket: 'RentItEase-c762e.firebasestorage.app',
iosBundleId: 'com.RentItEase.app.mobileApp',
  );
}
