CREATE INDEX IF NOT EXISTS "User_role_createdAt_idx" ON "User"("role", "createdAt");
CREATE INDEX IF NOT EXISTS "Property_ownerId_idx" ON "Property"("ownerId");
CREATE INDEX IF NOT EXISTS "Property_city_state_idx" ON "Property"("city", "state");
CREATE INDEX IF NOT EXISTS "Booking_propertyId_status_idx" ON "Booking"("propertyId", "status");
CREATE INDEX IF NOT EXISTS "Booking_tenantId_status_idx" ON "Booking"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "Invoice_userId_status_invoiceDate_idx" ON "Invoice"("userId", "status", "invoiceDate");
CREATE INDEX IF NOT EXISTS "Membership_userId_status_idx" ON "Membership"("userId", "status");
CREATE INDEX IF NOT EXISTS "Lease_tenantId_status_idx" ON "Lease"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "Payment_status_createdAt_idx" ON "Payment"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Notification_userId_isRead_createdAt_idx" ON "Notification"("userId", "isRead", "createdAt");
CREATE INDEX IF NOT EXISTS "Conversation_propertyId_idx" ON "Conversation"("propertyId");
CREATE INDEX IF NOT EXISTS "Conversation_ownerId_updatedAt_idx" ON "Conversation"("ownerId", "updatedAt");
CREATE INDEX IF NOT EXISTS "Conversation_tenantId_updatedAt_idx" ON "Conversation"("tenantId", "updatedAt");
CREATE INDEX IF NOT EXISTS "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");
CREATE INDEX IF NOT EXISTS "PropertyVisit_propertyId_visitDate_idx" ON "PropertyVisit"("propertyId", "visitDate");
CREATE INDEX IF NOT EXISTS "PropertyVisit_tenantId_visitDate_idx" ON "PropertyVisit"("tenantId", "visitDate");
CREATE INDEX IF NOT EXISTS "PremiumListing_userId_status_idx" ON "PremiumListing"("userId", "status");
