name: Backend CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Prisma generate
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Build Backend
        run: npm run build

      - name: Unit Tests
        run: npm run test:unit:properties
